name: OnPush

on:
  push:
    branches:
      - master
      - develop
      - release/*
    paths-ignore:
      - 'readme.md'
      - 'CHANGELOG.md'
      - 'docs/**'

env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/ngdenterprise/Build/_packaging/public/nuget/v3/index.json
  DOTNET_VERSION: '6.0.x'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  package:
    uses: ./.github/workflows/package.yml
  release:
    needs: [test, package]
    runs-on: ubuntu-latest
    steps:
    - name: Download Packages
      uses: actions/download-artifact@v3
      with:
        name: packages
        path: ./out
    - name: Push to Azure Artifacts
      if: ${{ (github.event_name == 'push') }}
      run: dotnet nuget push --source ${{ env.AZURE_ARTIFACTS_FEED_URL }} --api-key ${{ secrets.AZURE_ARTIFACTS_PAT }} out/*.nupkg